export const CALC_REVIEWS_AVERAGE = 'CALC_REVIEWS_AVERAGE';
export const REMOVE_REVIEWS = 'REMOVE_REVIEWS';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const EDIT_FEEDBACK_ID = 'EDIT_FEEDBACK_ID';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
