export const CALC_REVIEWS_AVERAGE = 'CALC_REVIEWS_AVERAGE';
export const REMOVE_REVIEWS = 'REMOVE_REVIEWS';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const EDIT_FEEDBACK_ID = 'EDIT_FEEDBACK_ID';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const FETCH_FEEDBACK_BEGIN = 'FETCH_FEEDBACK_BEGIN';
export const FETCH_FEEDBACK_SUCCESS = 'FETCH_FEEDBACK_SUCCESS';
export const FETCH_FEEDBACK_ERROR = 'FETCH_FEEDBACK_ERROR';
